CREATE TABLE Customer (
    CustomerId UNIQUEIDENTIFIER PRIMARY KEY NOT NULL,
    FirstName NVARCHAR(50) NOT NULL,
    LastName NVARCHAR(50) NOT NULL,
    EmailAddress NVARCHAR(255) NOT NULL,
    PhoneNumber NVARCHAR(50) NOT NULL
);

CREATE TABLE ErrorReport (
    Id INT NOT NULL IDENTITY(1,1),
    Description NVARCHAR(255) NOT NULL,
    EntryTime DATETIMEOFFSET NOT NULL,
    Status INT NOT NULL,
    CustomerId UNIQUEIDENTIFIER NOT NULL FOREIGN KEY REFERENCES Customer(CustomerId) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE Comments (
    Id INT NOT NULL IDENTITY(1,1),
    CommentString NVARCHAR(255) NOT NULL,
    Time DATETIME NOT NULL,
    ErrorReportId INT NOT NULL FOREIGN KEY REFERENCES ErrorReport(Id) ON DELETE CASCADE ON UPDATE CASCADE
);



